name: nginx-hexo
services:
    nginx-hexo:
        container_name: nginx-hexo
        environment:
            - UID=1000
            - GID=1000
            - GIT_REPO=https://git.xj9264.xyz/myproj/hexo.git
            - GIT_USER=test1234
            - GIT_PASSWORD=test1234
            - PORT=8081
            - HEXO_DIR=/app/hexo
            - HOST=xj9264.xyz
        network_mode: "bridge"
        ports:
            - 8081:8081
            # - 9000:9000
        # volumes:
            # - ~/hexo:/app/hexo
        image: nginx-hexo