FROM node:lts-alpine
LABEL maintainer="Gary"

RUN apk add --no-cache nginx git ca-certificates curl 
RUN	rm -f /etc/nginx/conf.d/default.conf \
    && mkdir -p /run/nginx \
    && npm config set registry https://registry.npmmirror.com \
    && npm install -g hexo-cli pm2 \
    && git config --global credential.helper store

COPY webhook.js /app/
COPY entrypoint.sh /
COPY hexo.conf /etc/nginx/http.d/
WORKDIR /app
ENTRYPOINT ["/entrypoint.sh"]
EXPOSE 8081
